### ISSUE TITLE
Root level modifications aren't applied correctly?

### ISSUE THREAD

**Issue by djMax** [bruth/jsonpatch-js#25]
This line: https://github.com/bruth/jsonpatch-js/blob/master/jsonpatch.js#L519 feeds the ORIGINAL document into each successive step. Shouldn't it be feeding in `result` instead of `document`?

**Comment by bruth** [comment]
From the spec:

> Each operation in the sequence is applied to the target document; the resulting document becomes the target of the next operation.

Nice catch. It is interesting no one has reported this before.

**Comment by djMax** [comment]
I think the reason is that it only affects the root key. Otherwise the changes are sort of fed back automatically.

**Comment by bruth** [comment]
Indeed.
